<a href="https://colab.research.google.com/github/oorona/testpage/blob/master/numpy_discord.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
Imax=100
Jmax=100
Kmax=5
Ia=np.arange(0,Imax,1)
Ja=np.arange(0,Jmax,1)
Ka=np.arange(0,Kmax,1)


In [2]:
SwNew=np.random.rand(Imax,Jmax,Kmax)

ResSwc=0.25
SwNew[SwNew<ResSwc]=ResSwc
SwNew[SwNew>1-ResSwc]=1-ResSwc

print (SwNew)


[[[0.39969837 0.28828053 0.42923968 0.27186593 0.56818372]
  [0.33933629 0.36676843 0.45681358 0.68681322 0.50869119]
  [0.37165643 0.28604862 0.39295436 0.43019456 0.75      ]
  ...
  [0.75       0.25       0.43904469 0.25       0.25      ]
  [0.39843604 0.5281167  0.27248626 0.75       0.57982293]
  [0.75       0.74015929 0.75       0.75       0.25      ]]

 [[0.75       0.25       0.65766704 0.25       0.75      ]
  [0.75       0.50660645 0.25       0.25       0.75      ]
  [0.6581103  0.75       0.75       0.45435247 0.75      ]
  ...
  [0.25       0.71820421 0.25       0.72358869 0.56575669]
  [0.61887114 0.75       0.33423536 0.56015796 0.75      ]
  [0.291871   0.75       0.58459424 0.34482335 0.38537812]]

 [[0.75       0.25       0.25       0.75       0.25      ]
  [0.25       0.33677327 0.75       0.25       0.66358242]
  [0.75       0.75       0.25       0.75       0.75      ]
  ...
  [0.39777406 0.75       0.75       0.75       0.71795596]
  [0.25842389 0.75       0.6345294